controllers:
    resource: ../src/Controller/
    type: attribute

cgv:
    path: /cgv
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'static/cgv.html.twig'

# route qui remplace la route présente dans HomeController.php
app_home: 
    path: /
    controller: App\Controller\HomeController::index

app_exo:
    path: /exo
    controller: App\Controller\ExoController::index